### ISSUE TITLE
Running SFINCS with docker GPU on windows

### ISSUE THREAD

**Issue by navass11** [Deltares/SFINCS#13]
I am trying to run my flood model with SFINCS through docker using the GPU in **Windows 10**. For this I have mounted the image via the file [Dockerfile.gpu](https://github.com/Deltares/SFINCS/blob/community_models/source/Dockerfile.gpu).

Once the image has been created I proceed to run my model through the command ```docker run --gpus all -v```.

It reads the model correctly but when it starts running the simulation it stops. 

I attach the file  [logfile.txt](https://github.com/Deltares/SFINCS/files/10731969/logfile.txt).

**Comment by Leynse** [comment]
This Issue has been solved now; depending on your exact windows 10 machine you can build this Dockerfile.gpu yourself and then run SFINCS succesfully on your local GPU setup. Thanks for raising this issue!
