### ISSUE TITLE
Windows download link seems to be broken

### ISSUE THREAD

**Issue by kettner** [Deltares/SFINCS#34]
Hi all,
The SFINCS model seems very promising, and I'm a big advocate for open source numerical models, so thank you for making the model source code available. One issue that I was made aware of is that the download link for windows is broken (it gives a browser timeout error (RR_CONNECTION_TIMED_OUT) when trying to get to the following URL: https://download.deltares.nl/en/download/sfincs/  ). It would be great if this gets fixed at some point.

Thanks!
Albert

**Comment by Leynse** [comment]
Hi Albert, I also saw the same this morning, and notified my ICT colleagues, thanks for letting us know!
Best, Tim

**Comment by Leynse** [comment]
Communicated now also with the rest of the SFINCS community: https://www.linkedin.com/feed/update/urn:li:activity:7077221610696404992?utm_source=share&utm_medium=member_desktop

**Comment by Leynse** [comment]
The SFINCS executable is now available from:
https://download2.deltares.nl/sfincs

As communicated here:
https://www.linkedin.com/feed/update/urn:li:activity:7077244811002408961?utm_source=share&utm_medium=member_desktop

Thanks for reporting the issue, and advocating for open source numerical models!

Best,
Tim
