### ISSUE TITLE
Backwards compatibility discharge and weir modelling issue

### ISSUE THREAD

**Issue by Leynse** [Deltares/SFINCS#35]

**Comment by Leynse** [comment]
- Problem arrises when running an old model with tidal and upstream discharge forcing, the fluxes are lower than with the old prerelease SVN openacc_11_rev394_01072022 version
- Seems to be related to runnin advection=0 with theta<1.0 (here 0.95)
- Might be related to added smoothing for that case in commit f8b95a2 of 01-11-2022

**Comment by keesnederhoff** [comment]
Latest revision might have resolved this. @Leynse: could please give this another try?

**Comment by Leynse** [comment]
Yes this is fixed in the recent main, excellent!
