### ISSUE TITLE
Build no longer works

### ISSUE THREAD

**Issue by Peter9192** [Deltares/SFINCS#55]
Docker build on main branch fails with `Fatal Error: Cannot open module file 'sfincs_infiltration.mod' for reading at (1): No such file or directory`.

It still works for 8e76c79cb659691d4bfe8be68e9c444dcb41a6e3, but fails after 3d3fe9ed93aff30cde1591703cf2aed44c5956ee.

**Comment by Peter9192** [comment]
Local build also fails

**Comment by Leynse** [comment]
sfincs_infiltration.f90 added to makefile.am
