### ISSUE TITLE
 [Error] x dimension not found. Use 'set_spatial_dims' functions with correct x_dim argument provided.

### ISSUE THREAD

**Issue by babuinorei** [Deltares/SFINCS#74]
Hello everyone, I am trying to derive data for the model in a netCDF format, I end up having the same Error regarding to the dimension.

I reproduced the netCDF build the same as one that worked (provided by Deltares) but I keep having the same  error.

The data is for the waterlevel forcing.

If you guys have anything that could help me it would be nice.

thank you and regards!

////////////////////////////////////////////////////traceback below:

Cell In[26], line 1
----> 1 sf.setup_waterlevel_forcing(geodataset='waterlevel_test',buffer=1000)

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt_sfincs\sfincs.py:1829, in SfincsModel.setup_waterlevel_forcing(self, geodataset, timeseries, locations, offset, buffer, merge)
   1826 # read waterlevel data from geodataset or geodataframe
   1827 if geodataset is not None:
   1828     # read and clip data in time & space
-> 1829     da = self.data_catalog.get_geodataset(
   1830         geodataset,
   1831         geom=region,
   1832         buffer=buffer,
   1833         variables=["waterlevel"],
   1834         time_tuple=(tstart, tstop),
   1835         crs=self.crs,
   1836     )
   1837     df_ts = da.transpose(..., da.vector.index_dim).to_pandas()
   1838     gdf_locs = da.vector.to_gdf()

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\data_catalog.py:876, in DataCatalog.get_geodataset(self, data_like, bbox, geom, buffer, variables, time_tuple, single_var_as_array, **kwargs)
    871 self._used_data.append(name)
    872 self.logger.info(
    873     f"DataCatalog: Getting {name} GeoDataset {source.driver} data"
    874     f" from {source.path}"
    875 )
--> 876 obj = source.get_data(
    877     bbox=bbox,
    878     geom=geom,
    879     buffer=buffer,
    880     variables=variables,
    881     time_tuple=time_tuple,
    882     single_var_as_array=single_var_as_array,
    883     logger=self.logger,
    884 )
    885 return obj

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\data_adapter\rasterdataset.py:353, in RasterDatasetAdapter.get_data(self, bbox, geom, buffer, zoom_level, align, variables, time_tuple, single_var_as_array, cache_root, logger)
    350     ds_out = ds_out[variables]
    352 # transpose dims to get y and x dim last
--> 353 x_dim = ds_out.raster.x_dim
    354 y_dim = ds_out.raster.y_dim
    355 ds_out = ds_out.transpose(..., y_dim, x_dim)

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\raster.py:294, in XRasterBase.x_dim(self)
    292 """Return the x dimension name."""
    293 if self.get_attrs("x_dim") not in self._obj.dims:
--> 294     self.set_spatial_dims()
    295 return self.attrs["x_dim"]

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\raster.py:362, in XRasterBase.set_spatial_dims(self, x_dim, y_dim)
    360     self.set_attrs(x_dim=x_dim)
    361 else:
--> 362     raise ValueError(
    363         "x dimension not found. Use 'set_spatial_dims'"
    364         + " functions with correct x_dim argument provided."
    365     )
    367 if y_dim is None:
    368     for dim in YDIMS:

ValueError: x dimension not found. Use 'set_spatial_dims' functions with correct x_dim argument provided.

**Comment by gutierrad** [comment]
Hi!

It seems to me that your question would be better suited here:
https://github.com/Deltares/hydromt_sfincs/issues

Hope this helps,
David

**Comment by babuinorei** [comment]
thank you very much!

**Comment by Leynse** [comment]
Thanks David!
Indeed post questions related to HydroMT-SFINCS (model setup) to that repository.
This one is for SFINCS kernel itself.

Thanks!
Tim

**Comment by babuinorei** [comment]
Thank you guys for the support!

problem solved!
