### ISSUE TITLE
`cdval` parameter is missing from the documentation

### ISSUE THREAD

**Issue by jamal919** [Deltares/SFINCS#99]
`cdval` parameter seems to be missing from the documentation. The description of this parameter seems to be merged with `cdwnd`. The parameter name should be inserted just before the following line - 

https://github.com/Deltares/SFINCS/blob/6d1e19a0540b1a1b16e87142ec901eb8118771cc/docs/parameters.rst?plain=1#L202

**Comment by Leynse** [comment]
Thanks a lot for pointing this out, it is added in the code now: https://github.com/Deltares/SFINCS/commit/cfa6c976bd9ca4ddaa200ed1aaed573bcc761440

Should be visible on Readthedocs online soon as well
